development:
  adapter: mysql
  encoding: utf8
  database: anoob_development
  username: root
  password: root
  socket: /var/run/mysqld/mysqld.sock

test:
  adapter: mysql
  encoding: utf8
  database: anoob_test
  username: root
  password: root
  socket: /var/run/mysqld/mysqld.sock

production:
  adapter: mysql
  encoding: utf8
  database: anoob_production
  username: root
  password: root
  socket: /var/run/mysqld/mysqld.sock
